CONFIG_GPIO=y

CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_DEVICE_NAME="NXS-Cont"

CONFIG_POWEROFF=y
CONFIG_HWINFO=y
CONFIG_PM=y
CONFIG_PM_DEVICE=y

CONFIG_FLASH=y