name: Zephyr build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: .

      - name: Init west workspace
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -p always -b xiao_ble -s .

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: nxs-controller-firmware
          path: build/zephyr/zephyr.uf2